### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by bradjones452** [uniplug/youtrack-docker#12]
Is it possible for you to add ssl to this project? We are having issues with the Agile boards and the 
"The live update connection is taking longer than expected. Please refer to the YouTrack reverse proxy configuration and verify that you have disabled buffering for connections that support live updates." message. The community suggests that we go to https to solve the issue.

Thanks Brad Jones.

**Comment by egregors** [comment]
@bradjones452 look's like, we have solved your problem: https://github.com/Egregors/youtrack-docker-compose

**Comment by bradjones452** [comment]
Awesome thanks….



Brad Jones.
______________
[cid:5B7844CF-A507-4854-907C-2AFAB0D768ED]

   BRAD JONES / sr. infrastructure manager
    email:  bjones@purepredictive.com
    cell:  801.560.1597  office:  801.890.5172

CONFIDENTIALITY NOTICE: This e-mail and any attachments are for the exclusive and confidential use of the intended recipient. If you received this in error, please do not read, distribute, or take action in reliance upon this message. Instead, please notify us immediately by return email and promptly delete this message and its attachments from your computer system.

**Comment by Raerten** [comment]
@bradjones452 
it seems the problem is that live update does not work over http.
you need to configure https on reverse proxy in a separate container (nginx, [Træfik ](https://hub.docker.com/_/traefik/) etc.).
