### ISSUE TITLE
About MaxMetaspaceSize

### ISSUE THREAD

**Issue by gongdo** [uniplug/youtrack-docker#14]
Currently, your youtrack startup script sets MaxMetaspaceSize as 250m. And this is an official(?) configuration according this: https://www.jetbrains.com/help/youtrack/standalone/Configure-JVM-Options.html

However, I experienced `java.lang.OutOfMemoryError: Metaspace` error like:

![image](https://user-images.githubusercontent.com/5451328/34595757-a7e07aea-f21d-11e7-9540-dfba45f4dae7.png)

I could resolve this problem by increasing MaxMetaspaceSize as 512m. Here's my youtrack.conf for supervisord. (It's exactly same as yours except MaxMetaspaceSize)

```
java -Xmx1g -XX:MaxMetaspaceSize=512m -Duser.home=/opt/youtrack -Ddatabase.location=/opt/youtrack/data -Ddatabase.backup.location=/opt/youtrack/backup -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Djetbrains.youtrack.disableBrowser=true -Djetbrains.youtrack.enableGuest=false -Djava.awt.headless=true -Djetbrains.youtrack.disableCheckForUpdate=true -Djava.security.egd=/dev/urandom -jar /opt/youtrack/bin/youtrack.jar 80
```

I'm not an expert for Java or Youtrack. I'm not sure what the configuration affects. If the configuration is okay, why don't you increase MaxMetaspaceSize?

**Comment by Raerten** [comment]
Hi,
I've made branch based on alpine image (#7) with increased MaxMetaspaceSize.
Can you try it https://github.com/uniplug/youtrack-docker/tree/alpine?

**Comment by gongdo** [comment]
@Raerten I tried it quickly with several dummy projects and issues, and it worked without memory error.
Good job!
