### ISSUE TITLE
Why does the container need a pseudo-TTY?

### ISSUE THREAD

**Issue by melhesedek** [uniplug/youtrack-docker#16]
README features `docker create` command without `-t` but then `docker run -t` in two other examples.

**Comment by Raerten** [comment]
yep, it's unnecessary
fix https://github.com/uniplug/youtrack-docker/commit/8b46a14120089924e056e1ed00a6fcb8c6bb20ee

**Comment by melhesedek** [comment]
There's one still left in a service example
```
$ grep -- -t README.md
ExecStart=/usr/bin/docker run -t \
```
