### ISSUE TITLE
Error with "send mail" in Version 6.5 and 7.0

### ISSUE THREAD

**Issue by niklasfyi** [uniplug/youtrack-docker#4]
Hello,

I get the following error when I try to send a test mail from within youtrack:

`Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.1und1.de, 587; timeout 30000; nested exception is: java.net.UnknownHostException: smtp.1und1.de. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.1und1.de, 587; timeout 30000; nested exception is: java.net.UnknownHostException: smtp.1und1.de`

Do I need to specify any additional settings? I am using the docker image within kubernetes

Thank you guys for you work :+1:

**Comment by Raerten** [comment]
sorry for the delay.
this error is not related to docke image, most likely image has no access to Internet

**Comment by niklasfyi** [comment]
Sorry that I forgot about this issue. We have fixed the problem. It had something to do with docker, but not your image ;)
