### ISSUE TITLE
Not able to run an archived docker instance of Youtrack

### ISSUE THREAD

**Issue by PlumCantaloupe** [uniplug/youtrack-docker#8]
I am trying to [save and archive a running docker container](https://linuxconfig.org/docker-container-backup-and-recovery) but when trying to run the saved docker image it stalls with several "Persistent class instance already registered for" warnings. Any way around this?

<img width="951" alt="screen shot 2017-04-17 at 6 48 55 am" src="https://cloud.githubusercontent.com/assets/264985/25087016/f7e9a7ae-2339-11e7-8656-696fe1e7aec1.png">

**Comment by Raerten** [comment]
Hi, do you use the same version of database?
In example DB stored externaly in folder /data/youtrack/data/
`
-v /data/youtrack/data/:/opt/youtrack/data/
`
